# Generated by Django 3.2.8 on 2021-11-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='titulo_post',
            field=models.CharField(max_length=2550, verbose_name='Título'),
        ),
    ]
