# Generated by Django 4.0 on 2021-12-15 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promocionalome',
            new_name='preco_marketing_promocional',
        ),
    ]
